Add advice on alcohol at events
rubynz/www pull request #24
Opened 2017-07-19 09:24 UTC by danielfone

Sneaked in a change for the Rails Camp details too.

<img width="997" alt="screen shot 2017-07-19 at 9 23 21 pm" src="https://user-images.githubusercontent.com/43041/28360082-86973886-6cc8-11e7-97f9-b6f7359a8f06.png">

2017-07-19 20:42 UTC, raquelxmoss requested changes
Nice! Please just change the font, then I am good for this to go out.

2017-07-19 20:42 UTC, raquelxmoss commented on events/alcohol-advice.html
> +  <link href="https://fonts.googleapis.com/css?family=Roboto:400,900" rel="stylesheet">
Could we please use the same font as the main page? It's [Poppins](https://fonts.google.com/specimen/Poppins)

2017-07-19 20:42 UTC, raquelxmoss commented on events/alcohol-advice.html
> +    please get in touch with the <a href="mailto:committee@ruby.nz">committee</a>. Thanks! ✨
🤔 Would it be gauche to throw in a 🍻 emoji? Haha

2017-07-20 12:17 UTC, danielfone commented
@raquelxmoss I've fixed fonts and added gauche. Let me know if you want me to squash.

2017-07-20 20:38 UTC, raquelxmoss approved these changes

2017-07-20 20:39 UTC, raquelxmoss commented
Looks good, merge and deploy whenever you like

2017-07-20 21:39 UTC, merged